cc_library(
    name="arrow",
    srcs=[
        "@arrow_repo//:cpp/src/arrow/array.cc",
        "@arrow_repo//:cpp/src/arrow/buffer.cc",
        "@arrow_repo//:cpp/src/arrow/builder.cc",
        "@arrow_repo//:cpp/src/arrow/column.cc",
        "@arrow_repo//:cpp/src/arrow/compare.cc",
        "@arrow_repo//:cpp/src/arrow/memory_pool.cc",
        "@arrow_repo//:cpp/src/arrow/pretty_print.cc",
        "@arrow_repo//:cpp/src/arrow/schema.cc",
        "@arrow_repo//:cpp/src/arrow/status.cc",
        "@arrow_repo//:cpp/src/arrow/table.cc",
        "@arrow_repo//:cpp/src/arrow/type.cc",

        "@arrow_repo//:cpp/src/arrow/io/file.cc",
        #"@arrow_repo//:cpp/src/arrow/io/hdfs.cc",
        #"@arrow_repo//:cpp/src/arrow/io/hdfs-internal.cc",
        "@arrow_repo//:cpp/src/arrow/io/interfaces.cc",
        "@arrow_repo//:cpp/src/arrow/io/memory.cc",

        #"@arrow_repo//:cpp/src/arrow/ipc/adapter.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/file.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/json.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/json-internal.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/metadata.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/metadata-internal.cc",
        #"@arrow_repo//:cpp/src/arrow/ipc/stream.cc",

        #"@arrow_repo//:cpp/src/arrow/jemalloc/memory_pool.cc",

        "@arrow_repo//:cpp/src/arrow/util/bit-util.cc",
        #"@arrow_repo//:cpp/src/arrow/util/file-to-stream.cc",
        #"@arrow_repo//:cpp/src/arrow/util/stream-to-file.cc",
    ],
    hdrs=[
        "@arrow_repo//:cpp/src/arrow/api.h",
        "@arrow_repo//:cpp/src/arrow/array.h",
        "@arrow_repo//:cpp/src/arrow/buffer.h",
        "@arrow_repo//:cpp/src/arrow/builder.h",
        "@arrow_repo//:cpp/src/arrow/column.h",
        "@arrow_repo//:cpp/src/arrow/compare.h",
        "@arrow_repo//:cpp/src/arrow/memory_pool.h",
        "@arrow_repo//:cpp/src/arrow/pretty_print.h",
        "@arrow_repo//:cpp/src/arrow/schema.h",
        "@arrow_repo//:cpp/src/arrow/status.h",
        "@arrow_repo//:cpp/src/arrow/table.h",
        "@arrow_repo//:cpp/src/arrow/type_fwd.h",
        "@arrow_repo//:cpp/src/arrow/type.h",
        "@arrow_repo//:cpp/src/arrow/type_traits.h",

        "@arrow_repo//:cpp/src/arrow/io/file.h",
        #"@arrow_repo//:cpp/src/arrow/io/hdfs.h",
        #"@arrow_repo//:cpp/src/arrow/io/hdfs-internal.h",
        "@arrow_repo//:cpp/src/arrow/io/interfaces.h",
        "@arrow_repo//:cpp/src/arrow/io/memory.h",
        #"@arrow_repo//:cpp/src/arrow/io/mman.h",
        #"@arrow_repo//:cpp/src/arrow/io/windows_compatibility.h",

        #"@arrow_repo//:cpp/src/arrow/ipc/adapter.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/file.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/json.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/json-internal.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/metadata.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/metadata-internal.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/stream.h",
        #"@arrow_repo//:cpp/src/arrow/ipc/util.h",

        #"@arrow_repo//:cpp/src/arrow/jemalloc/memory_pool.h",

        "@arrow_repo//:cpp/src/arrow/util/bit-util.h",
        #"@arrow_repo//:cpp/src/arrow/util/io-util.h",
        "@arrow_repo//:cpp/src/arrow/util/logging.h",
        "@arrow_repo//:cpp/src/arrow/util/macros.h",
        #"@arrow_repo//:cpp/src/arrow/util/random.h",
        "@arrow_repo//:cpp/src/arrow/util/visibility.h",
    ],
    strip_include_prefix="external/arrow_repo/cpp/src/",
)
